os: osx
language: generic
before_install:
    - brew update
    - virtualenv env -p python
    - source env/bin/activate
    - brew install qgis2
    - pip install -r requirements.txt
script: "pytest"
notifications:
    email:
        on_success: change
        on_failure: change
after_success:
    - codecov
cache: pip
